using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


/* In this program we will create an 8 ball game, which purpose is to ask a question, and a ramdom answer will be given by the game*/


namespace oop_lesson5_eightball
{
    class Program
    {
        static void Main(string[] args)
        {
            ///  Welcomes user to the game
            Console.WriteLine("*** Magic 8 Ball ***");
            Console.WriteLine();

            /*By using Console.Write we let the user to input something, so it can be use to randomize the answer*/


            Console.Write("Ask me a question ");
                string question = Console.ReadLine();

            List<string> magic8Ball = new List<string>();

            magic8Ball.Add("It is Certain");
            magic8Ball.Add("It is decidedly so");
            magic8Ball.Add("Without a doubt");
            magic8Ball.Add("Yes, definitely");
            magic8Ball.Add("You may rely on it");
            magic8Ball.Add("As I see it, yes");
            magic8Ball.Add("Most likely");
            magic8Ball.Add("Outlook good");
            magic8Ball.Add("Yes");
            magic8Ball.Add("Signs point to yes");
            magic8Ball.Add("Reply, hazy, try again");
            magic8Ball.Add("ask again later");
            magic8Ball.Add("Better not tell you now");
            magic8Ball.Add("cannot predict now");
            magic8Ball.Add("Concentrate and ask again");
            magic8Ball.Add("Don't count on it");
            magic8Ball.Add("My reply is no");
            magic8Ball.Add("My sources say no");
            magic8Ball.Add("Outlook not so good");
            magic8Ball.Add("Very doubtful");

            //The class randomAnswer will be use to access the list magic8Ball
            Random randomAnswer = new Random();

            //The range of the answers based on the list is from 1 to 20
            int answers = randomAnswer.Next(0, 19);

            //The console will store the random answer generated by the randomAnswer class, and it will use the answers variable to pick one
            //from 1 to 20

            Console.WriteLine(magic8Ball[answers]);

            Console.ReadLine();




        }
    }
}
